version: '3.8'
services:
  client:
    container_name: client_cba
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app
  server:
    container_name: server_cba
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/code
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    networks:
      - app
      - server_db
  db:
    container_name: db_cba
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE} 
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - server_db
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_cba
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${PMA_HOST}
    networks:
      - server_db
networks:
  server_db:
    driver: bridge
  app:
    driver: bridge
    